estrutura checkout feita
tryber/sd-03-trybeer-1 pull request #16
Opened 2020-09-30 19:43 UTC by lucasfranca90

2020-09-30 21:00 UTC, nato-re approved these changes

2020-10-03 12:04 UTC, lcdlima requested changes

2020-10-03 12:04 UTC, lcdlima commented on back-end/models/checkoutModel.js
> +const checkout = async () => connection()
Eu fiquei confusa com a nomeação dessas funções. 
Essa função você nomeou como checkout, mas na verdade você está fazendo um getAllSales, não?
E o finish order que seria o checkout, certo?

2020-10-05 20:45 UTC, lcdlima approved these changes

2020-10-05 20:46 UTC, merged